# Generated by Django 5.2.7 on 2025-11-23 07:39

import recipes.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, storage=recipes.storage_backends.MediaStorage(), upload_to='recipes'),
        ),
    ]
