# Generated by Django 5.2.7 on 2026-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fav_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], db_index=True, default='intermediate', max_length=12),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
